"""Core schema definitions for risk signals and event types."""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class EventType(str, Enum):
    """Categorical event types identified from unstructured text."""
    GEOPOLITICAL = "Geopolitical"
    MACROECONOMIC = "Macroeconomic"
    CREDIT_EVENT = "Credit Event"
    MERGER_ACQUISITION = "Merger/Acquisition"
    PRODUCT_LAUNCH = "Product Launch"
    REGULATORY = "Regulatory"
    EARNINGS = "Earnings"
    OTHER = "Other"


class RiskSignal(BaseModel):
    """Structured risk signal generated by the AI/NLP engine."""
    ts: datetime = Field(..., description="Timestamp of the event or signal generation")
    ticker: str = Field(..., description="Target stock ticker symbol (e.g. AAPL)")
    source: str = Field(..., description="Data source identifier (e.g. GDELT, NewsAPI, Twitter)")
    text_id: str = Field(..., description="Unique source document or tweet ID")
    headline: str = Field(..., description="Processed headline or text summary")
    sentiment_score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description="Sentiment score bounded between -1.0 (bearish/negative) and 1.0 (bullish/positive)"
    )
    event_type: EventType = Field(..., description="Classified financial or geopolitical event type")
    impact_score: float = Field(
        ...,
        ge=1.0,
        le=10.0,
        description="Predicted market impact severity score bounded between 1.0 and 10.0"
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence score bounded between 0.0 and 1.0"
    )
    event_confidence: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Event classification confidence score bounded between 0.0 and 1.0"
    )
    secondary_event: Optional[EventType] = Field(
        None,
        description="Runner-up event type or None"
    )
    attribution_weight: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Portfolio attribution weight for multi-ticker or broadcast items (1/n)"
    )
    matched_triggers: Optional[List[str]] = Field(
        None,
        description="Specific trigger terms or regex patterns matched in the text"
    )
    impact_components: Optional[Dict[str, float]] = Field(
        None,
        description="Explainable breakdown of impact score contributions"
    )
    is_broadcast: Optional[bool] = Field(
        False,
        description="Flag indicating whether text was a broadcast item across multiple tickers"
    )
    is_analyst_action: Optional[bool] = Field(
        False,
        description="Flag indicating whether event was an equity analyst rating or price-target action"
    )


